// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwNco7LbCqkvv09OE_LPc0XcKGF-rmv4',
    appId: '1:981444420360:web:11ea41eff527c9c50f02bd',
    messagingSenderId: '981444420360',
    projectId: 'flut-tube-9e32a',
    authDomain: 'flut-tube-9e32a.firebaseapp.com',
    storageBucket: 'flut-tube-9e32a.appspot.com',
    measurementId: 'G-D8DD28L75V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ78PAOV-Ej_yD0BbhKVv_5elBp4N6qOU',
    appId: '1:981444420360:android:856a095a2e037acc0f02bd',
    messagingSenderId: '981444420360',
    projectId: 'flut-tube-9e32a',
    storageBucket: 'flut-tube-9e32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPP5NtfDWUzvFJxgVHI7ibAXbuYXDDoI',
    appId: '1:981444420360:ios:4346ee1c0045bebf0f02bd',
    messagingSenderId: '981444420360',
    projectId: 'flut-tube-9e32a',
    storageBucket: 'flut-tube-9e32a.appspot.com',
    iosBundleId: 'com.example.flutTube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtPP5NtfDWUzvFJxgVHI7ibAXbuYXDDoI',
    appId: '1:981444420360:ios:a31e921b5b4aaaf80f02bd',
    messagingSenderId: '981444420360',
    projectId: 'flut-tube-9e32a',
    storageBucket: 'flut-tube-9e32a.appspot.com',
    iosBundleId: 'com.example.flutTube.RunnerTests',
  );
}
